# networks:
services:
    qmk:
        container_name: qmk
        image: qmk:jiaex
        restart: "no"
        # user: "1000:1000"
        entrypoint: ["sleep", "infinity"]
        volumes:
            - ./:/root/qmk_firmware
